<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class NewCar extends Model
{
  protected $fillable = [
      'enquiry_date',
       'name',
       'contact1',
       'contact2',
       'address',
       'qualification',
       'email',
       'office_address',
       'office_contact',
       'mother_name',
       'spouse_name',
       'spouse_occupation',
       'spouse_contact',
       'no_of_dependents',
       'reference1_name',
       'reference1_contact',
       'reference1_address',
       'reference2_name',
       'reference2_contact',
       'reference2_address',
       'vehicle_brand',
       'vehicle_model',
       'vehicle_color',
       'vehicle_dealer',
       'vehicle_financer',
       'vehicle_booking_amount',
       'vehicle_ex_showroom',
       'vehicle_1_tcs',
       'vehicle_depot',
       'vehicle_insurance',
       'vehicle_rto',
       'vehicle_warranty',
       'vehicle_accessories',
       'vehicle_onroad',
       'vehicle_discount',
       'vehicle_cost',
       'vehicle_finance_approved',
       'vehicle_emi',
       'vehicle_stampduty',
       'vehicle_downpayment',
       'vehicle_part1',
       'vehicle_part2',
       'dealer_payment',
       'dealer_disbursement',
       'dealer_balance',
       'emi_date',
       'loan_account_number',
       'post_delivery_documents',
       'invoice_number',
       'invoice_photo',
       'insurance_number',
       'insurance_photo',
       'rcbook_number',
       'rcbook_photo',
       'fastag_number',
       'fastag_photo',
       'pancard_number',
       'pancard_photo',
       'lightbill_number',
       'lightbill_photo',
       'aadharcard_number',
       'aadharcard_photo'
  ];
}
